{% set name = "tcolorpy" %}
{% set version = "0.0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 642d4105c59e6fac6c1a2e04962a8a4c363cb7070f956969c4af5e2a780b5ef3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - releasecmd
  run:
    - python >=3.5

test:
  imports:
    - tcolorpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/thombashi/tcolorpy
  summary: tcolopy is a Python library to apply true color for terminal text.
  dev_url: https://github.com/thombashi/tcolorpy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
